export interface FileAttachment {
  id: string;
  name: string;
  size: number;
  type: string;
  content?: string; // base64 encoded (legacy)
  url?: string; // Supabase public URL (new for storage)
}

export interface Message {
  id?: string; // Optional: Generated by DB on insert
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  attachments?: FileAttachment[];
}

export interface Settings {
  apiKey: string;
  baseUrl: string;
  model: string;
}

export interface Conversation {
  id: string;
  title: string;
  created_at: string; // ISO string for display
  updated_at: string; // ISO string for sorting
  project_id?: string; // Optional FK to project
}

export interface Project {
  id: string;
  title: string;
  created_at: string;
  updated_at: string;
}